name: Build and Deploy Bookdown Site

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch. Adjust if needed.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Install system dependencies (including Pandoc)
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc pandoc-citeproc

    # Step 3: Set up R
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3'  # Specify the R version you want to use

    # Step 4: Install R dependencies
    - name: Install R Dependencies
      run: |
        Rscript -e 'install.packages("bookdown")'
        Rscript -e 'install.packages("rmarkdown")'

    # Step 5: Build the Bookdown site
    - name: Build Bookdown Site
      run: |
        Rscript -e 'bookdown::render_book("index.Rmd", output_dir = "_book")'

    # Step 6: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _book
        publish_branch: gh-pages  # The branch where GitHub Pages is served from
