name: Build and Deploy Bookdown Site

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch. Adjust if needed.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc pandoc-citeproc  # Install Pandoc and citation processor

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3'  # Specify the R version you want to use

    - name: Install Dependencies
      run: |
        Rscript -e 'install.packages("bookdown")'
        Rscript -e 'install.packages("rmarkdown")'

    - name: Build Bookdown Site
      run: |
        Rscript -e 'rmarkdown::clean_site(preview = FALSE)'
        Rscript -e 'rmarkdown::render_site(encoding = 'UTF-8')'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _book
        publish_branch: gh-pages  # The branch where GitHub Pages is served from
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './_book'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
